### ISSUE TITLE
Multi-app support - running multiple Vite instances with separate bundles

### ISSUE THREAD

**Issue by johnknott** [mrdotb/live_react#25]
Hi! First, thanks for this great library. I'm trying to build an app with multiple frontends (main app and admin panel) and was wondering if LiveReact has any support for this use case?
Ideally, I'd like to:

* Run separate vite instances (on different ports) in dev
* Generate separate JS bundles in production (because my admin panel will be large and I don't want that JS to be sent to every user)
* Have separate frontend directories (e.g. frontend/app, frontend/admin)

I tried using an umbrella app as a workaround but ran into some tricky path resolution issues. Have you considered this use case before? Would love to hear your thoughts on potential approaches.

I know I could have separate phoenix apps in a monorepo which would work but I'd rather keep things in one application if possible.

**Comment by mrdotb** [comment]
Hi,

LiveReact don't need to do anything special for this case.

_Run separate vite instances (on different ports) in dev_
Why ? I don't see any benefit.

_Generate separate JS bundles in production (because my admin panel will be large and I don't want that JS to be sent to every user)_
In vite / esbuild / webpack config you can have more than one entry point which allow you to generate different bundles. 
You need to setup two entrypoints. Then you add an extra root layout that use the other bundle.

In your vite config file add admin.js file or similar
```
        input: {
          app: path.resolve(__dirname, "./js/app.js"),
          admin: path.resolve(__dirname, "./js/admin.js")
        },
```

Create a new root layout that use this bundle
```
<!DOCTYPE html>
<html lang="en" class="[scrollbar-gutter:stable]">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content={get_csrf_token()} />
    <.live_title suffix=" · Phoenix Framework">
      {assigns[:page_title] || "LiveReactExamples"}
    </.live_title>
    <LiveReact.Reload.vite_assets assets={["/js/admin.js", "/css/admin.css"]}>
      <link phx-track-static rel="stylesheet" href={~p"/assets/admin.css"} />
      <script type="module" phx-track-static type="text/javascript" src={~p"/assets/admin.js"}>
      </script>
    </LiveReact.Reload.vite_assets>
  </head>
  <body class="min-h-screen bg-background font-sans antialiased">
    {@inner_content}
  </body>
</html>
```

In the router you will need to add pipeline that put the correct layout
```
  pipeline :public do
    plug :browser
    plug :put_root_layout, {TtrWeb.Layouts, :root}
    plug :put_layout, {TtrWeb.Layouts, :app}
  end

  pipeline :admin do
    plug :browser
    plug :put_root_layout, {TtrWeb.Layouts, :admin_root}
    plug :put_layout, {TtrWeb.Layouts, :admin_app}
  end
```

**Comment by mrdotb** [comment]
No worry. I did not use live_react in projects that have two js entry point yet.
You will have to rework the react components folder organisation to have two separates list of components.
